---
title: "MaSigPro"
author: "luozhihui"
date: "2019/10/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r get significant genes, echo=FALSE}
library("maSigPro")
Time = c(rep(0, 18), rep(2, 18), rep(4, 18), rep(7, 18), rep(10, 18)) 
Replicates = rep(1:30, each=3)
Control = c(rep(1,18), rep(0, 72))
K27ac = rep(c(rep(1,3), rep(0,15)), 5)
K27me3 = rep(c(rep(0,3), rep(1,3), rep(0,12)), 5)
K4me1 = rep(c(rep(0,6), rep(1,3), rep(0,9)), 5)
K4me3 = rep(c(rep(0,9), rep(1,3), rep(0,6)), 5)
K9me2 = rep(c(rep(0,12), rep(1,3), rep(0,3)), 5)
K9me3 = rep(c(rep(0,15), rep(1,3)), 5)

CRC.design = cbind(Time,Replicates, Control, K27ac,K27me3, K4me1, K4me3, K9me2, K9me3)
#rownames(CRC.design) <- paste("Array", c(1:90), sep = "")
sample_vector = c()
for (we in c("ctrl", "2weeks", "4weeks", "7weeks", "10weeks")){
  for (mark in c("H3K27ac", "H3K27me3", "H3K4me1", "H3K4me3", "H3K9me2", "H3K9me3")){
    for ( rep in c("1", "2" ,"3")){
      sample = paste(paste(we, rep, sep="_"), mark, sep="_")
      sample_vector = c(sample_vector, sample)
    }
  }
}
rownames(CRC.design) = sample_vector
d <- make.design.matrix(CRC.design, degree = 3)
#print(d)
#training data
df = read.delim("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/expression_10000_ensembl.txt", sep=",", header=T, row.names=1, check.names=FALSE)
df = df[1:700, ]
df = data.matrix(df)
df = scale(df, center = TRUE, scale = TRUE)
fit <- p.vector(df, d, Q = 0.05, MT.adjust = "BH", min.obs = 20)
tstep <- T.fit(fit, step.method = "backward", alfa = 0.05)

get<-get.siggenes(tstep, vars="all")
cluster_result = see.genes(get$sig.genes, k = 9, newX11 = FALSE)

```
## RNA expression MaSigPro result
this chunck is used for analysis the RNA expression cluster.  

```{r drawing, echo=FALSE}
Time = c(rep(0, 3), rep(2, 3), rep(4, 3), rep(7, 3), rep(10, 3)) 
Replicates = rep(1:5, each=3)
Control = c(rep(0,15))
RNA = c(rep(1,15))

RNA.design = cbind(Time,Replicates, Control, RNA)  
sample_vector = c()
for (we in c("week0", "week2", "week4", "week7", "week10")){
  for ( rep in c("1", "2" ,"3")){
      sample = paste(we, rep, sep="_")
      sample_vector = c(sample_vector, sample)
  }
}

rownames(RNA.design) = sample_vector
d <- make.design.matrix(RNA.design, degree = 4)

count_table = read.csv("/home/zhihl/Project/CRC/RNA_analysis/count_table.txt", row.names=1, check.names = FALSE, sep="\t")
colnames(count_table) = sample_vector

df = count_table
df = data.matrix(df)
df = scale(df, center = TRUE, scale = TRUE)
fit <- p.vector(df, d, Q = 0.05, MT.adjust = "BH", min.obs = 5)
tstep <- T.fit(fit, step.method = "backward", alfa = 0.05)
save(tstep, file = "/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/masigpro_all_degree4_20191114.RData")

get<-get.siggenes(tstep, vars="all")
pdf("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_result_total.pdf")
cluster_result = see.genes(get$sig.genes, k = 9, newX11 = FALSE)
dev.off()


#for (i in 1:9){
gene_detail = read.delim("/home/zhihl/Project/CRC/RNA_analysis/mart_export_mouse_geneid_symbol.txt", sep="\t", header=T)

essemble_to_entrez = function (deg_list){
  entrez_map = as.data.frame(unlist(as.list(org.Mm.egENSEMBL2EG)))
  ind<-match(deg_list, rownames(entrez_map))
  deg_eg = entrez_map[ind,]
  return(deg_eg)
}

ensembl_to_symbol = function(ensemble_list, name){
  if (name == "mouse")
  {symbol = gene_detail[match(ensemble_list, gene_detail$ensembl_gene_id),"external_gene_name"]}
  if (name == "human")
  {symbol = human_gene_detail[match(ensemble_list, human_gene_detail$ensembl_gene_id),"external_gene_name"]}
  return(as.vector(symbol)) 
}



i = 1
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")


library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()

ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()



i = 2
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()




i = 3
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()

ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()



i = 4
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


i = 5
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()

ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()




i = 6
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


i = 7
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()

ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()



i = 8
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()

ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


i = 9
clu1 = cluster_result$cut[cluster_result$cut == i]
#clu9 = cluster_result$cut[cluster_result$cut == 9]
#clu15 = cluster_result$cut[cluster_result$cut == 15]
#deg_list = c(names(clu8), names(clu9), names(clu15))

symbol_vector = ensembl_to_symbol(names(clu1), "mouse")
gene_table = data.frame(ensembl = names(clu1), symbol = symbol_vector)
table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_gene_list_cluster", i , ".txt", sep="")
write.table(gene_table, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")

library(org.Mm.eg.db)
library("clusterProfiler")
ego <- enrichGO(gene          = names(clu1),
                keyType       = "ENSEMBL",
                OrgDb         = "org.Mm.eg.db",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/RNA_", i , ".txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , ".pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()

ego <- enrichKEGG(gene          = essemble_to_entrez(names(clu1)),
                  keyType       = "kegg",
                  organism      = "mmu",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01)

table_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/rna_", i , "_KEGG.txt", sep="")
write.table(ego@result, table_name, sep="\t", quote=F, row.names=F, col.names = T, na="NA", eol="\n")
pdf_name = paste("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/rna/pdf_", i , "_KEGG.pdf", sep="")
pdf(pdf_name, width=10, height=10)
dotplot(ego, showCategory=15)
dev.off()


#}
```
## try
```{r experiment, echo=FALSE}

v_vector = get$sig.genes$groups.vector[c(-1,-2,-16)]
cluster_result = see.genes(get$sig.genes, k = 9, newX11 = FALSE, groups.vector=v_vector)
```


## make new matrix
```{r matrix, echo=FALSE}
library("maSigPro")
Time = c(rep(2, 18), rep(4, 18), rep(7, 18), rep(10, 18), rep(2, 18), rep(4, 18), rep(7, 18), rep(10, 18)) 
Replicates = rep(1:48, each=3)
Control = c(rep(1,72), rep(0, 72))
K27ac = rep(c(rep(1,3), rep(0,15)), 8)
K27me3 = rep(c(rep(0,3), rep(1,3), rep(0,12)), 8)
K4me1 = rep(c(rep(0,6), rep(1,3), rep(0,9)), 8)
K4me3 = rep(c(rep(0,9), rep(1,3), rep(0,6)), 8)
K9me2 = rep(c(rep(0,12), rep(1,3), rep(0,3)), 8)
K9me3 = rep(c(rep(0,15), rep(1,3)), 8)

CRC.design = cbind(Time,Replicates, Control, K27ac,K27me3, K4me1, K4me3, K9me2, K9me3)
#rownames(CRC.design) <- paste("Array", c(1:90), sep = "")
sample_vector = c()
for (we in c("ctrl2", "ctrl4", "ctrl7", "ctrl10", "2weeks", "4weeks", "7weeks", "10weeks")){
  for (mark in c("H3K27ac", "H3K27me3", "H3K4me1", "H3K4me3", "H3K9me2", "H3K9me3")){
    for ( rep in c("1", "2" ,"3")){
      sample = paste(paste(we, rep, sep="_"), mark, sep="_")
      sample_vector = c(sample_vector, sample)
    }
  }
}
rownames(CRC.design) = sample_vector
d <- make.design.matrix(CRC.design, degree = 3)

df = read.delim("/home/zhihl/Project/CRC/Chip_analysis/MaSigPro/expression_10000_ensembl.txt", sep=",", header=T, row.names=1, check.names=FALSE)
df_sub2 =  df[,colnames(df)[1:18]]
colnames(df_sub2) = rownames(CRC.design)[1:18]
df_sub4 =  df[,colnames(df)[1:18]]
colnames(df_sub4) = rownames(CRC.design)[19:36]
df_sub7 =  df[,colnames(df)[1:18]]
colnames(df_sub7) = rownames(CRC.design)[37:54]
df_sub10 =  df[,colnames(df)[1:18]]
colnames(df_sub10) = rownames(CRC.design)[55:72]

new_df = data.frame(df[, -1:-18], df_sub2, df_sub4, df_sub7, df_sub10, check.names = FALSE) 

new_df = new_df[1:700, ]
new_df = data.matrix(new_df)
new_df = scale(new_df, center = TRUE, scale = TRUE)
fit <- p.vector(new_df, d, Q = 0.05, MT.adjust = "BH", min.obs = 20)
tstep <- T.fit(fit, step.method = "backward", alfa = 0.05)

get<-get.siggenes(tstep, vars="all")
pdf("hello.pdf")
cluster_result = see.genes(get$sig.genes, k = 9, newX11 = FALSE)
dev.off()
```